# Generated by Django 5.0.7 on 2024-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
