# Generated by Django 5.0.7 on 2024-07-27 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_digitalmarketpost_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceForAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalPrice', models.CharField(max_length=200)),
                ('TranctionsAmount', models.CharField(max_length=200)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('ConnectCorrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
