# Generated by Django 5.0.7 on 2024-07-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_priceforadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceforadd',
            name='TotalPrice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='priceforadd',
            name='TranctionsAmount',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='priceforadd',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
